
server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  cloud:
    config:
      server:
        native:
         search-locations: classpath:config/ #配置文件目录
        git:
          uri: https://github.com/sun3stones/my-cloud
          search-paths: config-server/src/main/resources/config
          username: 2554353621@qq.com
          password: sun3stones.
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: springcloud
      password: springcloud
  application:
    name: service-config
  profiles:
   # active: git  # 从git读取配置
    active: native # 从本地读取配置

management:
  endpoints:                  #SpringCloud 2.0.0版本以后暴露接口方式
    web:
      exposure:
        include: "*"