
server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/ #配置文件目录
  application:
    name: service-config
  profiles:
    active: native  # 从本地读取配置