wechat:
  token: sun3stones
  AppId: wxb3047c48b4907e88
  AppSecret: cbaf50af6ae9a4a44025d9f6ccf3310a
  EncodingAESKey: ODoRUts4QA2olvyjNRh5tVQZ25RERHLLQLN9jxYWWuC
name: sunlei

# 驱动配置信息
#
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/mytest?useSSL=false&characterEncoding=utf-8
    username: sunlei
    password: sun3stones
    driverClassName: com.mysql.jdbc.Driver
#连接池的配置信息
## 初始化大小，最小，最大
  druid:
    initialSize: 5
    minIdle: 5
    maxActive: 20
## 配置获取连接等待超时的时间
    maxWait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=100
