#API网关配置
zuul:
  #路由配置
  routes:
    mywechat:    #认证服务
      #响应的路径
      path: /wechat/**
      #敏感头信息
      sensitiveHeaders:
      #重定向到的服务（根据服务id名称从注册中心获取服务地址）
      serviceId: mywechat
  #添加代理头
  add-proxy-headers: true
